### ISSUE TITLE
Add a background task to clean up the .cdHistory file

### ISSUE THREAD

**Issue by vincpa** [vincpa/z#10]
The .cdHistory file can become clogged over time causing z to slow down. A background task should validate all paths and update the in-memory copy.

**Comment by ralesi** [comment]
@vincpa, is there currently any method to validate the paths in `.cdHistory`?  I need to clean it up from removed directories and wanted to check before doing it by hand.

**Comment by vincpa** [comment]
I feel as though background task would complicate things quite a bit. It might be simpler to check for the paths existence before entering the directory.

What do you think?

-----Original Message-----

**Comment by ralesi** [comment]
That's what I was thinking too,  we don't need a background check,  just one during execution. 


Rich






On Mon, Feb 29, 2016 at 1:28 PM -0800, "Vince Panuccio" <notifications@github.com> wrote:










I feel as though background task would complicate things quite a bit. It might be simpler to check for the paths existence before entering the directory.



What do you think?



-----Original Message-----

**Comment by vincpa** [comment]
Do you  have time to implement this? :-)

**Comment by ralesi** [comment]
Yes,  I have something already,  will send a PR.

**Comment by vincpa** [comment]
This has been implemented as a command line option, -c
