### ISSUE TITLE
z.psm1 commands are not consistent with z.sh

### ISSUE THREAD

**Issue by ralesi** [vincpa/z#14]
I have noticed that the command line arguments used for z.psm1 are not consistent with the normal z.  Is there a reason for the departure?  All the below options are placed in the 'o' parameter alias, even though technically `c` and `l` should be allowed to run in conjunction with ranking options, and can be made as separate command line flags.  

```
z.sh options :
OPTIONS
       -c     restrict matches to subdirectories of the current directory
       -e     echo the best match, don't cd
       -h     show a brief help message
       -l     list only
       -r     match by rank only
       -t     match by recent access only
       -x     remove the current directory from the datafile

EXAMPLES
       z foo         cd to most frecent dir matching foo
       z foo bar     cd to most frecent dir matching foo, then bar
       z -r foo      cd to highest ranked dir matching foo
       z -t foo      cd to most recently accessed dir matching foo
       z -l foo      list all dirs matching foo (by frecency)
```

I have a patch I can submit getting this to work if interested. I left the ranking options in `-o`, but listing and current directory would then be separate flags.

**Comment by vincpa** [comment]
Sure thing. Can you please send a pull request to the development branch.

master is used for "production" and is linked to a few package management sites. Thanks.
