### ISSUE TITLE
Add tab support like in z.sh

### ISSUE THREAD

**Issue by ralesi** [vincpa/z#17]
We can either add tab support,  or depend on one of the tab completion plugins used in powershell.

**Comment by vincpa** [comment]
Great idea

**Comment by Yhubee** [comment]
@vincpa any news about this?

**Comment by vincpa** [comment]
It would be great it someone could help me out with this idea 😄 I would love tab support.

**Comment by vincpa** [comment]
The implementation is quite simple. I'll look at getting this done this week sometime.

**Comment by Yhubee** [comment]
@vincpa Great! Too much of a noob to be able to help :grin:

**Comment by vincpa** [comment]
Done. New release https://www.powershellgallery.com/packages/z/1.1.5

**Comment by Yhubee** [comment]
@vincpa  Thank you!
