### ISSUE TITLE
Version 1.1.5 Update Issue

### ISSUE THREAD

**Issue by Yhubee** [vincpa/z#26]
@vincpa  None of the instructions on the PSGallery page worked so I had to use `Install-Module z` which returned an error that I had to use `Install-Module z -Force` to install the updated version side-by-side with v. 0.0. which returned this error:

![about-the-update](https://cloud.githubusercontent.com/assets/22277667/19533174/9713b5f4-9636-11e6-9833-bd3a6b3091a4.jpg)

- Windows v. 1607

**Comment by vincpa** [comment]
Thanks for taking the time to submit this issue.

Because this module overrides the `cd` command, PowerShell is simply warning you about this. As the error suggests, use -AllowClobber to install.

Let me know how you go.

**Comment by Yhubee** [comment]
@vincpa , is it safe to override the `cd` command? 
Sorry if this is noob-ish.

**Comment by Yhubee** [comment]
OK, I just decided to `-AllowClobber` after seeing the most recent issue opened and it didn't work. 

![install-module](https://cloud.githubusercontent.com/assets/22277667/19746646/3739b9b4-9bcf-11e6-9b6f-b787a9f7f979.jpg)

Then I decided to do `Install-Module z -Force` again and it worked.

**Comment by vincpa** [comment]
I'm glad it worked.

Just a note, the reason "AllowClobber" wasn't recognised is because you are using an older version of PowerShellGet. You can install the new version here https://www.powershellgallery.com/packages/PowerShellGet/1.1.1.0
