### ISSUE TITLE
Powershell on CentOS 7.4 

### ISSUE THREAD

**Issue by trgrassijr55** [vincpa/z#36]
Installed Powershell on my Cent OS VM running on VMware.
Cent OS was 7.2 when I installed powershell and I had powershell working locally.
was trying invoke-command to a windows 2012 R2 Server which from My Windows 10 computer using Powershell 5 I can invoke-command and pssession to the same windows 2012r2 server with no issues.

Installed OMI but NTLM did not work so I decided to upgrade CENTOS to 7.4

After reboot of centos  I can no longer start powershell

[root@tgcs018 tmp]# powershell
-bash: powershell: command not found

How do I get powershll working on centOS

Thank you

**Comment by vincpa** [comment]
This is not the right place to be posting PowerShell issues unless they relate to z.

Please see here https://github.com/PowerShell/PowerShell
