### ISSUE TITLE
.git folder is downloaded from the PowerShell Gallery

### ISSUE THREAD

**Issue by brainplot** [vincpa/z#42]
I don't know if this was a mistake or an oversight but I noticed, on the [PowerShell Gallery page](https://www.powershellgallery.com/packages/z/1.1.9) for this repo, that the file list comprehends the whole `.git/` folder. This is rather unusual and makes the module bigger than it should be (arguably not by much, but still 😉).

**Comment by vincpa** [comment]
Holy cow! I'll have to sort that out.

**Comment by vincpa** [comment]
Issue resolved. Thanks for letting me know :)
