### ISSUE TITLE
Exception calling "Parse" with "1" argument(s): "Input string was not in a correct format." 

### ISSUE THREAD

**Issue by chaliy** [vincpa/z#5]
Not sure what is wrong. Ping me if you need more details.

 C:\Users\Mike\Projects>
$ cd .\studies-octo-adventure\
System.Management.Automation.MethodInvocationException: Exception calling "Parse" with "1" argument(s): "Input string was not in a correct format." ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at CallSite.Target(Closure , CallSite , RuntimeType , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()

**Comment by kidchenko** [comment]
Você ganhou $25 de José para a sua primeira viagem!

No Airbnb você pode descobrir lugares únicos no mundo inteiro para se hospedar com anfitriões locais.


Basta se cadastrar até 24 de Agosto de 2015 para receber um desconto de R$ 87 em sua primeira viagem de R$ 261 ou mais.





Aceitar convite
http://www.airbnb.com.br/c/jbarbosa220?eluid=0&email=reply%2b0052e5b15e2ad27a03a233d3cede6766a7c9419419182f9792cf0000000110ac05a492a169ce020e07f5%40reply.github.com&euid=2d703f2f-d5d7-d027-7951-75ce0d06f8cf&ri=26136166&s=1

Obrigado,
A Equipe do Airbnb

P.O. Box 410807, San Francisco, CA 94121

Cancelar
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDA1MmU1YjE1ZTJhZDI3YTAzYTIzM2QzY2VkZTY3NjZhN2M5NDE5NDE5MTgyZjk3OTJjZjAwMDAwMDAxMTBhYzA1YTQ5MmExNjljZTAyMGUwN2Y1QHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbiIsInV1aWQiOiIyZDcwM2YyZi1kNWQ3LWQwMjctNzk1MS03NWNlMGQwNmY4Y2YifQ==&mac=4bNTM7_jdpOPrFJAPb6Dcj8I91o=

### Airbnb ###

**Comment by kidchenko** [comment]
Você ganhou $25 de José para a sua primeira viagem!

No Airbnb você pode descobrir lugares únicos no mundo inteiro para se hospedar com anfitriões locais.


Basta se cadastrar até 24 de Agosto de 2015 para receber um desconto de R$ 87 em sua primeira viagem de R$ 261 ou mais.





Aceitar convite
http://www.airbnb.com.br/c/jbarbosa220?eluid=0&email=reply%2b0052e5b1283b35729075b18a3925cf5e61c999477150f0d292cf0000000110ae846392a169ce020e07f5%40reply.github.com&euid=9ea082a8-5517-74ec-16a8-22e0a0da5d4c&ri=26136163&s=1

Obrigado,
A Equipe do Airbnb

P.O. Box 410807, San Francisco, CA 94121

Cancelar
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDA1MmU1YjEyODNiMzU3MjkwNzViMThhMzkyNWNmNWU2MWM5OTk0NzcxNTBmMGQyOTJjZjAwMDAwMDAxMTBhZTg0NjM5MmExNjljZTAyMGUwN2Y1QHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbiIsInV1aWQiOiI5ZWEwODJhOC01NTE3LTc0ZWMtMTZhOC0yMmUwYTBkYTVkNGMifQ==&mac=gKSCKghcbo5Z82g3xdapdJVpXbA=

### Airbnb ###

**Comment by kidchenko** [comment]
Você ganhou $25 de José para a sua primeira viagem!

No Airbnb você pode descobrir lugares únicos no mundo inteiro para se hospedar com anfitriões locais.


Basta se cadastrar até 24 de Agosto de 2015 para receber um desconto de R$ 87 em sua primeira viagem de R$ 261 ou mais.





Aceitar convite
http://www.airbnb.com.br/c/jbarbosa220?eluid=0&email=reply%2b0052e5b1cfa39c24352538c47a5fc13f73dffbe19373481292cf0000000110ac214992a169ce020e07f5%40reply.github.com&euid=30da3d3c-f164-2d57-b657-d448f1c81a26&ri=26136164&s=1

Obrigado,
A Equipe do Airbnb

P.O. Box 410807, San Francisco, CA 94121

Cancelar
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDA1MmU1YjFjZmEzOWMyNDM1MjUzOGM0N2E1ZmMxM2Y3M2RmZmJlMTkzNzM0ODEyOTJjZjAwMDAwMDAxMTBhYzIxNDk5MmExNjljZTAyMGUwN2Y1QHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbiIsInV1aWQiOiIzMGRhM2QzYy1mMTY0LTJkNTctYjY1Ny1kNDQ4ZjFjODFhMjYifQ==&mac=tlXIb1QlGemGIkre0vlFETkbT_8=

### Airbnb ###

**Comment by kidchenko** [comment]
Você ganhou $25 de José para a sua primeira viagem!

No Airbnb você pode descobrir lugares únicos no mundo inteiro para se hospedar com anfitriões locais.


Basta se cadastrar até 24 de Agosto de 2015 para receber um desconto de R$ 87 em sua primeira viagem de R$ 261 ou mais.





Aceitar convite
http://www.airbnb.com.br/c/jbarbosa220?eluid=0&email=reply%2b0052e5b10581c92ec634ec399543edfe61ad79cab3b661b592cf0000000110ac19a092a169ce020e07f5%40reply.github.com&euid=34a1f01d-85cc-b67f-69e0-2490538820e8&ri=26136165&s=1

Obrigado,
A Equipe do Airbnb

P.O. Box 410807, San Francisco, CA 94121

Cancelar
https://www.airbnb.com/email/unsubscribe?token=eyJlbWFpbF9hZGRyZXNzIjoicmVwbHkrMDA1MmU1YjEwNTgxYzkyZWM2MzRlYzM5OTU0M2VkZmU2MWFkNzljYWIzYjY2MWI1OTJjZjAwMDAwMDAxMTBhYzE5YTA5MmExNjljZTAyMGUwN2Y1QHJlcGx5LmdpdGh1Yi5jb20iLCJjYXRlZ29yeSI6InJlZmVycmFscyIsInRlbXBsYXRlIjoiaW52aXRhdGlvbiIsInV1aWQiOiIzNGExZjAxZC04NWNjLWI2N2YtNjllMC0yNDkwNTM4ODIwZTgifQ==&mac=EC6w-Iwl7vSYel_IovA9DKNY5So=

### Airbnb ###
