### ISSUE TITLE
Remove historical entry

### ISSUE THREAD

**Issue by badmotorfinger** [vincpa/z#7]

**Comment by deadcoder0904** [comment]
@badmotorfinger was wondering what's the command for this? is it just `-clean` or can i remove individual entry?

**Comment by deadcoder0904** [comment]
i tried `z 'a/b/' -Remove` but that still shows it in history/autocomplete.

**Comment by badmotorfinger** [comment]
@deadcoder0904 - The clean command simply removes directory entries which are unreachable or no longer exist. It does not allow individual entries to be removed.

**Comment by deadcoder0904** [comment]
im guessing removing individual entries doesn't exist?

**Comment by badmotorfinger** [comment]
Correct. The best thing to do is run clean and remove all invalid entries.
