### ISSUE TITLE
Breaks pushd/popd

### ISSUE THREAD

**Issue by togakangaroo** [vincpa/z#8]
W:\temp> pushd foobar
    W:\temp\foobar> popd
    W:\temp\foobar> get-command pushd
    
    CommandType     Name                                               ModuleName
    -----------     ----                                               ----------
    Alias           pushd -> pushdX                                    z
    W:\temp\foobar>

This is a big problem when scripts on the machine use pushd/popd!

**Comment by vincpa** [comment]
The pushdX simply wraps pushd. It will be transparent to any scripts calling pushd. What is the problem you are experiencing ?

**Comment by togakangaroo** [comment]
This code should pop me back to the initial directory shouldn't it?

Using push-location and bypassing pushdx works just fine

**Comment by vincpa** [comment]
I see. I will take a look. Sorry for any inconvenience caused.

**Comment by togakangaroo** [comment]
Awesome. I've been meaning to take a look at how proxies worked in ps so thank you so much for the example as well!

**Comment by vincpa** [comment]
No problem. Don't forget to star the repo if you like it :)
